### ISSUE TITLE
Dependency Injection: Container

### ISSUE THREAD

**Issue by lhaze** [pcah/python-clean-architecture#1]
I know two design patterns of DI Container (is there any other?):

  **A.** an argument of every DI-aware class constructor
  **B.** a singleton (probably in the global scope or scope of the container class)

I find singletons a contradiction of the clean architecture: a design pattern hard to isolate in the testing process and a security threat in the production. I'll take option A.

A good example of DI library is [ekiro/haps](https://github.com/ekiro/haps) with an unfortunate exception of Container design -- they have taken option B. I think it would be nice to build a solution based on their code and refactor it into option A.

**Comment by lhaze** [comment]
Example of usage:

```python
# interfaces.py
class HeaterInterface:
    pass


# some_dependent.py (manual usage of DI Container)
class CoffeeMaker:

    def __init__(container: Container):
        self.heater = container.find_by_interface(HeaterInterface)
        self.pump = container.find_by_name('a_pump')

    def make_coffee(self):
        return f"heater: {self.heater}\npump: {self.pump}"

# some_implementations.py
class Heater(HeaterInterface):

    def __repr__(self):
        return f'<Heater id={id(self)}>'


class Pump(PumpInterface):

    def __repr__(self):
        return f'<Pump id={id(self)}>'

# app.py
container = Container()
Container.register_by_interface(interface=HeaterInterface, constructor=Heater)
Container.register_by_name(name='a_pump', constructor=Pump)

# eventually
my_coffee_maker = CoffeeMaker(container)
```

**Comment by lhaze** [comment]
I consider placing the `dependency_injection.py` at the `utils` package (not at the domain/application). We may consider a Schema (placed at the `dharma.data`) which uses DI objects. And we don't want to find the `domain` package to be dependent on the `data` package. Module dependency should be directing from the `domain` to the `data`, not the opposite way.

Let's place DI module at the `dharma.utils.dependency_injection` module.

**Comment by jakos** [comment]
@lhaze You can assign this issue to me.

**Comment by lhaze** [comment]
Take into account issue #9 when designing API as it will be one of the most valuable features of the DI.

**Comment by lhaze** [comment]
Do you want to do sth more here or is this task to be closed? Pass it to me, if you don't want anything from it.

**Comment by jakos** [comment]
I will implement find/register_by_interface methods. Then you can close it.
