### ISSUE TITLE
Architecture: should Interactor and Presenter be coupled? 

### ISSUE THREAD

**Issue by lhaze** [pcah/python-clean-architecture#45]
Reference [2] (The Source of our Principles and Assumptions) presents `Interactor` component as defining two interfaces:

- `InputPort` aka `InputBoundary`, which is owned and implemented by the Interactor; this is an obvious part of the pattern and it's easy to implement.
- `OutputPort` aka `OutputBoundary`, which is owned by the Interactor, but implemented by the `Presenter`, outside of the application layer.

I'm fine with the design, but I find it tricky to meet all the assumptions in the latter boundary. The key question is: should Interactor and Presenter be coupled? The [1] delves into details and I just sumarize it below.

References:
1. [SO question: Clean Architecture: Use case containing the presenter or returning data?](https://softwareengineering.stackexchange.com/questions/357052/clean-architecture-use-case-containing-the-presenter-or-returning-data/357066#357066)
2. [The Uncle Bob: The Clean Architecture (figures)](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html)

**Comment by lhaze** [comment]
#### An Interactor which calls the presenter

The second solution: an Interactor which calls a Presenter.
```python
def controller(presenter, some_data):
    request_model = RequestModel(some_data)
    interactor = Interactor(presenter, some_dependency, other_dependency)
    # ... and here's the application layer call
    interactor(request_model)
```
Benefits:
- No close coupling between controllers and presenters. Building request models and orchestrating components by the controller has nothing to do with presentation process.

Drawbacks:
- This is not functional at all. Any test on the controller has to check side effects made on the presenter. I don't find it clean and easy to read.
- All web frameworks I know implement "return the response" pattern for their controllers. They don't print anything like CLI frameworks, send any data via message broker like microservices used to do. Should we align to this imperative pattern?

**Comment by lhaze** [comment]
@jakos, would you like to state your opinion about this topic? I recommend reading [2] as it gives quite nice analysis.

**Comment by lhaze** [comment]
Lately I've heard an argument that makes me almost convinced to design nr 2 (an Interactor which calls the presenter). It goes like this:

> We [web developers] are quite familiar and used to a pattern where an Interactor just returns data and respective Controller just passes them somewhere (i.e. to a renderer, a View, etc). This is a simple case due to synchronous and stateless nature of HTTP protocol. The rest of the world does not have such simplicity: desktop or mobile applications, asynchronous microservices or any interactive interface have to support concurrent and/or distributed request processing. It may mean that the Presenter may work on a different thread (e.g. UI thread) or publish to a different machine than the Controller works. Orchestrating the Presenter and the Controller as independent Components contributes to The Clean Architecture design at the layer of integration Interactors into different application environments.

**Comment by jakos** [comment]
@lhaze 
After reading discussion [1] I'm for the second solution. I think i'ts exactly what Uncle Bob said:

> For example, consider that the use case needs to call the presenter. However, this call must not be direct because that would violate The Dependency Rule: No name in an outer circle can be mentioned by an inner circle. So we have the use case call an interface (Shown here as Use Case Output Port) in the inner circle, and have the presenter in the outer circle implement it.

But what about the drawbacks? Testing is very important for me and I can't just ignore this issue. Maybe Interactor could just return the Presenter? Then it could be tested or maybe even used to return response like in classic web framework. That would be only an option, because like you stated in last comment Presenter could do something totally independent - publish to different machine etc. We could just examine it's state during tests.

**Comment by lhaze** [comment]
Ok, I think I'm convinced to solution # 2. Adequate pull request is welcomed, maybe it is my responsibility though.

I think clean design of test process would lead to `TestPresenter` implementation, which would just collect response data. It would have test helper methods as well. It could be not do bad.
