### ISSUE TITLE
Formulate the Principles for the library

### ISSUE THREAD

**Issue by lhaze** [pcah/python-clean-architecture#56]
Until today, the library was developed without its principles stated explicitly. Although they exist, they are scattered between some issue descriptions, chats with fellow developers and, of course, articles and lectures that are sources of inspiration.

Prepare:
* a doc with a list of the Principles and a set of subarticles describing its interpretation
* an exempt to place inside `README.md`
* a note within `CONTRIBUTING.md` with a link to the doc

**Comment by lhaze** [comment]
#### 1. Domain *First* Design

Domain should be *the first thing* you can start to develop on the first day of the project. No choice of a framework should be required -- you may not discover yet enough information needed to choose one. Similarly, neither infrastructure configuration nor developer toolset should be required. You should be able to start by describing your domain with pseudocode.

References:
> For most software projects, the primary focus should be on the domain and domain logic.
> Eric Evans (2003), [Domain Driven Design](https://www.amazon.com/exec/obidos/ASIN/0321125215/domainlanguag-20)

>  A good software architecture allows decisions about frameworks, databases, web-servers, and other environmental issues and tools, to be deferred and delayed. A good architecture makes it unnecessary to decide on Rails, or Spring, or Hibernate, or Tomcat or MySql, until much later in the project.
> Robert Martin (2011), [Screaming Architecture](https://blog.cleancoder.com/uncle-bob/2011/09/30/Screaming-Architecture.html)

**Comment by lhaze** [comment]
#### 2. Plain Old *Business* Objects

The core of the application should be expressible with objects as simple as possible. Entities should not be entangled with neither the persistence framework nor validation schemes (compare to the concept of "[Plain Old Java Objects](https://en.wikipedia.org/wiki/Plain_old_Java_object)"). This makes the way frameworks like SQLAlchemy, Django, etc. leading to inappropriate and unsuitable design. The same goes for all the business logic objects: values (aka value objects), services and events. The catchphrase is consistent with the rule # 1 and [The Single Responsibility Principle](https://web.archive.org/web/20150905081024/http://www.objectmentor.com/resources/articles/srp.pdf).

Quotes:
> "We wondered why people were so against using regular objects in their systems and concluded that it was because simple objects lacked a fancy name. So we gave them one, and it's caught on very nicely."
> Martin Fowler (2000), [POJO](https://www.martinfowler.com/bliki/POJO.html)

**Comment by lhaze** [comment]
#### 3. Layered design
#### 4. Loose coupling
#### 5. To be open to reimplementation
#### 6. Batteries included: integrations with frameworks

**Comment by lhaze** [comment]
4. Loose coupling
5. To be open to reimplementation
6. Batteries included: integrations with frameworks

**Comment by lhaze** [comment]
#### 4. Loose coupling

[Loose coupling](https://en.m.wikipedia.org/wiki/Loose_coupling) is a design technique of deffering architecture decisions (vide # 1) and improving code reusability. It also provides a clean way to achive  separation of layers (vide # 3).

This library uses Dependency Injection technique with [its own implementation](https://github.com/pcah/python-clean-architecture/blob/master/pca/utils/dependency_injection.py), because we didn't want to use existing DI libraries, based on global state. Our DI Container is a [non-global Singleton by single instance](https://softwareengineering.stackexchange.com/a/40610) and it is an explicit (and almost always the only one) dependency of any library's component.

**Comment by lhaze** [comment]
5. To be open to reimplementation
6. Batteries included: integrations with frameworks

**Comment by lhaze** [comment]
#### 6. Batteries included: integrations with frameworks

**Comment by lhaze** [comment]
@jakos, I need your help and a review. Tell me if there is something I've forgot or make it unclear or ambiguous.

**Comment by lhaze** [comment]
Excerpt:

1. **Domain First Design.** Building an application should begin with its business intent and without any decision about a framework or other technical details.
2. **Keep it simple and straightforward.** There's a great value of having simple objects. Use dataclasses. Decompose your components to have single responsibility components, but only as far as to be straightforward in your intents.
3. **Layered architecture.** Keep domain & application logic pure. Separate them in layers, the same goes for technical details for a framework & the whole system/hardware environment. Dependencies between layers should point only inwards, with domain in the core. You can have more layers if you feel a need, but keep in mind that every layer is a cost to maintain.

**Comment by jakos** [comment]
@lhaze 
I'ts good. Really. I would merge it as it is now. You can always modify it later.

**Comment by lhaze** [comment]
Done.
