### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by jakos** [pcah/python-clean-architecture#7]
Let's start using pytest for this project. The sooner the better.

**Comment by lhaze** [comment]
I don't mean to worry you but you have too check your eyesight :wink: The project has pytest for a long long time. Check `requirements-test.txt`, `setup.py` and `tox.ini`. You can run it localy with pytest CLI, with `. /setup.py test` or using `tox`.

But yet there are some things to do:
- clean `tox.ini` from obsolete settings
- setup Travis CI
- setup coveralls service

**Comment by lhaze** [comment]
Closing as wontfix -- already done.
